name: Brad Fitzwater's Blog
description: Building stuff.
meta_description: "Building stuff"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://bradfitzwater.com'

# Details for the RSS feed generator
url:            'http://bradfitzwater.com'
author:         'Brad Fitzwater'
exclude:        [Thumbs.db]
